### PR TITLE
Note the default value of size

### PR DESCRIPTION
**Pull request by Noitidart**
It's not clear by reading docs that size is 1 by default. This might help clear that up.

### CODE REVIEW

**Review by dai-shi — COMMENTED** [review]
Thanks for the change, but this is auto-generated part. Can you somehow change the jsdoc part? Please try `yarn apidoc`.

**Comment by dai-shi** [comment]
@Noitidart ?

**Comment by Noitidart** [comment]
Oh shoooot, so sorry I forgot about this. I think I didn't even see in my inbox sorry about that! Yes will do that, super busy with an urgent Stripe integration on a side project, will do this soon as I get.

**Comment by dai-shi** [comment]
@Noitidart In case you missed it.

**Comment by Noitidart** [comment]
Oh gosh yes I got sooo busy with looking for a new job and then my side work. Thanks for reminder! I'll try to hit this, this weekend.

**Pull request closed without merging**
