### PR TITLE
invoke trackMemo if returning an object from input object

### LINKED ISSUE #7: Incorrect memoization when reading an unchanged property of a changed object
Codesandbox reproduction: https://codesandbox.io/s/keen-tree-r7pp2

I know this is probably a general issue with the model and so not something that can be fixed, but I think it's important to note anyway. Here's the example from my codesandbox:

```
const initialState = { pet: { type: "cat", weight: 20 } };
const changedState = { pet: { type: "cat", weight: 40 } };

const getCat = memoize((state) => {
  if (state.pet.type === "cat") {
    return state.pet;
  } else {
    return null;
  }
});

console.log(getCat(initialState)) // { type: "cat", weight: 20 }
console.log(getCat(changedState)) // { type: "cat", weight: 20 }, should be { type: "cat", weight: 40 } instead
```

In this example, `proxy-memoize` "sees" the `state.pet.type` access, and so decides to just return the previous result if `state.pet.type` is equal to the last `state.pet.type`, even though the new and previous result should have different `weight` values. Again, I don't know if there's a good solution for this, but I think it's worth it to note the issue.

### PR DESCRIPTION
**Pull request by dai-shi**
close #7 

This fixes the specific case reported.
There might be some other edge cases to behave unexpectedly, so further experiments are welcomed.

### CODE REVIEW

**Review by jeremy-deutsch — APPROVED** [review]
I don't know how the code works, but branch passed my failing tests in #9, so it looks good to me :)

**Comment by dai-shi** [comment]
#9 is merged.

The way it works is when `trackMemo(state.pet)` is called, it will throw away the tracking info under that object. So, `state.pet.type`access is recorded just as `state.pet`.

**Comment by dai-shi** [comment]
I just noticed I forgot to push the spec file I created. It exists as uncommitted locally... Now as we have tests from #9, I discard it.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/proxy-memoize/v/0.2.3

**Pull request merged**
