### PR TITLE
update proxy-compare and re-export replaceNewProxy

### PR DESCRIPTION
**Pull request by dai-shi**
taking the update in https://github.com/dai-shi/proxy-compare/pull/41

### CODE REVIEW

**Review by hayond — APPROVED** [review]
Look good to me, thanks for this great change

**Comment by dai-shi** [comment]
@hayond Please use the csb build **seriously**. (I mean, preferably in production, if possible.)
I'm not planning to merge this anytime soon, until I get really good sign/feedback/confirmation.

**Comment by hayond** [comment]
> Please use the csb build seriously. (I mean, preferably in production, if possible.)

ok sure, no problem, I also will write some examples in the CodeSandbox, though I don't use it very often, but I will try a more complex scenario to verify the changes.

**Comment by hayond** [comment]
hi, @dai-shi I am trying use this csb in my daily work, but I got a type issue of the parameter of `replaceNewProxy`, how can I make it correct? usually, for using with other libs, I often import some types from them, extends, pass generic type or force case ;), but for this method, there isn't any type I can use from `proxy-memoize`, I am not a good type developer :), so maybe I missed some type usage.

image

**Comment by dai-shi** [comment]
Is `TinyProxyPolyfill` your function?
You can type it like original Proxy, and it should just pass.
(I need more info to help.)

https://codesandbox.io/s/react-typescript-forked-qn2ssx?file=/src/App.tsx
It works like this, but partly because it's `any`.

**Comment by hayond** [comment]
Ah, I see, I try your writing, it works after I make the function as any... thanks.

`TinyProxyPolyfill ` is my implementation of Proxy, since our work team has a limit hard requirement for dependencies, I don't want to import `proxy-polyfill` to make misunderstanding, though it can import as function, but need effort to explaining ^_^

**Comment by hayond** [comment]
@dai-shi hihi, sorry for late response ^_^, I am stuck in my other work recently, today I continue to finish the integration of this lib, I found a error when I use codesandbox, it throws `(0 , _proxyMemoize.default) is not a function`, I also switch to use your csb, still has the same error, colud you help take a look? thanks.

can check this demo: https://codesandbox.io/s/react-typescript-forked-8j44uu?file=/src/App.tsx

**Comment by dai-shi** [comment]
Can you check this? https://github.com/dai-shi/proxy-memoize#importing-package

**Comment by hayond** [comment]
> Can you check this? https://github.com/dai-shi/proxy-memoize#importing-package

ah, let me try, seems I didn't read doc carefully.

**Comment by hayond** [comment]
@dai-shi it works with this format `import proxyMemoize from 'proxy-memoize/dist/index.modern.js';`, but I have to ignore the type issue, is the error just happened on codesandbox? and for normal development I still can use esm import format, right?

**Comment by dai-shi** [comment]
Ah, types doesn't work with hacked import path. You need to configure tsconfig.
```json
        "baseUrl": ".",
        "paths": {
            "proxy-memoize/dist/index.modern.js": [
                "node_modules/proxy-memoize/dist/src/index.d.ts"
            ]
        }
```
https://codesandbox.io/s/goofy-goldwasser-yfo1zl?file=/tsconfig.json

If it happens with normal dev environment, we may need to look for a better solution.

**Comment by hayond** [comment]
sure, for my daily usage, seems can work correctly, only found error in codesandbox, let me try more, thanks

**Comment by hayond** [comment]
> sure, for my daily usage, seems can work correctly, only found error in codesandbox, let me try more, thanks

oh, wrong conclusion... seems my daily usage also encountered this error, I will use the format you mentioned above, and add the configuration in the `tsconfig.json` as temporary solution. I will check later, hopefully we can find better solution.

image

**Comment by hayond** [comment]
@dai-shi can work with this usage

```
import proxyMemoizeModule from 'proxy-memoize';
const proxyMemoize = proxyMemoizeModule.default;
```

I think it's caused by the `index.modern.js`, export default using `export{s as default}` instead of `export default s`

**Comment by dai-shi** [comment]
I think it's not a problem: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export

The problem is a bundler (or transpiler) which doesn't support native ESM.
I think it doesn't use `index.modern.js` but `index.umd.js` instead.

**Comment by hayond** [comment]
> The problem is a bundler (or transpiler) which doesn't support native ESM.

yeah, maybe my working webpack version doesn't support this format, let me try the `index.umd.js`, thanks.

**Comment by dai-shi** [comment]
I think webpack uses `index.umd.js`, even though the syntax is ESM `import`. So, there's a mismatch.

```js
const proxyMemoize = require('proxy-memoize');
```
would work with CJS and `index.umd.js`. But, 🤷‍♂️ .

**Comment by hayond** [comment]
@dai-shi hi, I saw your updates, would you like to merge this MR to master and publish a new version as well?

since I used the CSB version in my daily work for some time, me and my colleagues used for some scenarios, seems no problem, and I prepare to put my tool (based on proxy-compare) to live usage, so I'd like to use regular version instead of CSB.

**Comment by dai-shi** [comment]
> seems no problem

This is important to hear.
If it works good for you and you find no problems, let's merge.

**Comment by hayond** [comment]
> If it works good for you and you find no problems, let's merge.

yeah, great, thanks!

**Comment by dai-shi** [comment]
https://www.npmjs.com/package/proxy-memoize/v/1.2.0

**Pull request merged**
